# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Newman Tests by Postman.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # 30 minute (0 - 59), 23 hour (0 - 23), * (Todos) day of the month (1 - 31), * (Todos) month (1 - 12)
    - cron:  '30 23 * * *'

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
        # 1 - Step - Install dependences.
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: npm install -g newman
      - run: npm install -g newman-reporter-htmlextra

      # 2 -Step - Run the POSTMAN collection
      - name: Step 2 - Run POSTMAN collection
        if: always()
        continue-on-error: true
        run: |
          newman run collections/Reserva.postman_collection.json -r htmlextra --reporter-htmlextra-browserTitle "RDC QUALITY" -r htmlextra --reporter-htmlextra-title "RDC Test Api Automation" --reporter-htmlextra-export testResults/RDC Test_Api_Automation.html


      
     
